Curs_15_Django/pet_adoption_agency/pet_adoption_agency/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'pets.views.error_404'
urlpatterns = [
    path('pets/', include('pets.urls')),
    path('admin/', admin.site.urls),
]

Curs_15_Django/pet_adoption_agency/pets/urls.py
from django.conf.urls.static import static
from django.urls import path
from . import views

# from . -> din folderul curent

app_name = 'pets'
# urlpatterns = [
#     path('', views.pets, name='all_pets'),
#     path('<int:pet_id>/', views.pet_detail, name='pet_detail'), #vom avea un /pets/id
#     path('pet/', views.pet_add, name='add')
# ]
urlpatterns = [
    path('', views.PetsView.as_view(), name='all_pets'),
    path('<int:pk>/', views.PetDetailView.as_view(), name='pet_detail'), #vom avea un /pets/id
    path('pet/', views.PetCreateVeiew.as_view(), name='add')

] + static('static')

Curs_15_Django/pet_adoption_agency/pets/models.py
from django.db import models

# Create your models here.
PET_TYPES = [
    ('cat', 'Cat'),
    ('dog', 'Dog'),
    ('rabbit', 'Rabbit')
]


class Pet(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField(null=False)
    gender = models.CharField(max_length=1)
    species = models.CharField(max_length=6, choices=PET_TYPES)

    def __str__(self):
        return f"{self.name} - {self.age} - {self.gender} - {self.species}"

Curs_15_Django/pet_adoption_agency/pets/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Pet
from django.urls import reverse, reverse_lazy
from django.views import generic


# Create your views here.

# view este functia care va genera ce se va afisa in pagina web.

# def index(request):
#     return HttpResponse("Hello from pets_index")
#
#
# def pets(request):
#     pets_list = Pet.objects.all()  # ORM prin care accesam direct baza de date
#     return render(request, 'all_pets.html', {"pets": pets_list})
#
#
# def pet_detail(request, pet_id):
#     pet = get_object_or_404(Pet, pk=pet_id)
#     return render(request, 'pet_detail.html', {'pet': pet})
#
#
def error_404(request, exception):
    return render(request, 'error.html', {'error_message': 'Eroare'})
#
# def pet_add(request):
#     pet_details = request.POST.dict()
#     try:
#         pet = Pet(name=pet_details['name'], gender=pet_details['gender'],
#                   age=pet_details['age'], species=pet_details['species'])
#         pet.save()
#     except KeyError:
#         return render(request, 'error.html', {'error_message': 'Invalid pet details'})
#     return HttpResponseRedirect(reverse('pets:all_pets'))

class PetsView(generic.ListView):
    template_name = 'all_pets.html'
    context_object_name = 'pets'

    def get_queryset(self):
        return Pet.objects.all()


class PetDetailView(generic.DetailView):
    model = Pet
    template_name = 'pet_detail.html'

class PetCreateVeiew(generic.CreateView):
    model = Pet
    fields = ['name','age','gender','species']
    success_url = reverse_lazy('pets:all_pets') #reverse_lazy asteapta pana in ultima secunda
    #ca sa faca operatiunea ceruta, doar daca e necesar

Curs_15_Django/pet_adoption_agency/pets/templates/add_pet_form.html
<form action="{% url 'pets:add' %}" method="post">
    {% csrf_token %} <!-- csrf = cross site request forgery - este un secret unic
    pentru a proteja aplicatia server de requesturi straine -->
    <fieldset>
        <label for="name">
            Name:
        </label>
        <input type="text" name="name" id="name"> <br>
        <label for="age">
            Age:
        <input type="number" name="age" id="age"> <br>
        <label for="gender">
            Gender:
        </label>
        <label for="gender(F)">
            Female
        </label>
        <input type="radio" name="gender" id="gender(F)" value="F">
        <label for="gender(M)">
            Male
        </label>
        <input type="radio" name="gender" id="gender(M)" value="M"> <br>
        <label for="species">
            Species:
        </label>
        <input type="text" name="species" id="species"> <br>
        </label>
    </fieldset>
    <input type="submit" value="Add">
</form>

Curs_15_Django/pet_adoption_agency/pets/templates/all_pets.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pets</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
</head>
<body>
{% if pets %}
    <ul>
        {% for pet in pets %}
        <li>
            <a href="{%url 'pets:pet_detail' pet.id %}"> {{ pet }} </a>
        </li>
        {% endfor %}
    </ul>
{% endif %}
{% include "add_pet_form.html" %}
</body>
</html>

Curs_15_Django/pet_adoption_agency/pets/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
{{ error_message }}
</body>
</html>

Curs_15_Django/pet_adoption_agency/pets/templates/pet_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ pet.name }}</title>
</head>
<body>
{{ pet }}

</body>
</html>